### ISSUE TITLE
Mirror ?

### ISSUE THREAD

**Issue by jbruxelle** [LibertAntoine/PlantAI#4]
Still planning to use Mirror ? 
Did not see any Mirror relative classes/components : be careful with this, you might want to use NetworkTransform or NetworkAnimator to share movement, anims, etc... through network !
If not done yet, make sure to check Mirror documentation so that you won't have to rebuild things.  :)

**Comment by hdgnd** [comment]
Hello Julian!
Thanks for your interest with the project but we actually do not use Networking on this one. That is why you cannot see any Mirror relative things.
This is a simple AI project where some plants grow in an environment! 
We will make sure to write a good README about it. 😄
